---
guid: a1b2c3d4-e5f6-4789-a1b2-c3d4e5f67890
name: Carousel Layout
description: Transforme l'interface Jellyfin en layout type Netflix avec des carrousels horizontaux pour films, séries et animés
overview: Affichage personnalisé en carrousels pour Jellyfin
category: General
owner: peterdu1109
versions:
  - version: 1.0.0
    changelog: |
      - Version initiale
      - Affichage en carrousels horizontaux
      - Catégories: Nouveautés, Top 10, Continuer à regarder, Recommandés
      - Catégories par genre
      - Badges pour nouveaux épisodes et qualité (4K/HD)
      - Thème sombre type Netflix
      - Page de configuration complète
    targetAbi: 10.11.0.0
    sourceUrl: https://github.com/peterdu1109/Nouveaut-s--Top-10/releases/download/v1.0.0/JellyfinCarouselPlugin.dll
    checksum: TO_BE_GENERATED
    timestamp: 2026-02-05T10:00:00Z
